helm:
  parameters:
  - name: backend.image.tag
    value: sha-30929ae
    forcestring: true
  - name: createSecrets
    value: "false"
    forcestring: false
  - name: frontend.image.tag
    value: sha-30929ae
    forcestring: true
  - name: image.name
    value: ghcr.io/shreyasshelar/schema-vis-frontend
    forcestring: true
