{{- if and .Values.cloudflared.enabled .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: schema-vis-cloudflared-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schema-vis.labels" . | nindent 4 }}
type: Opaque
stringData:
  TUNNEL_TOKEN: {{ .Values.cloudflared.tunnelToken | required "cloudflared.tunnelToken is required" | quote }}
{{- end }}
