apiVersion: v1
kind: Secret
metadata:
  name: schema-vis-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schema-vis.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.backend.secrets.SPRING_DATASOURCE_PASSWORD | required "backend.secrets.SPRING_DATASOURCE_PASSWORD is required" | quote }}
  POSTGRES_USER:     {{ .Values.postgres.user | quote }}
  POSTGRES_DB:       {{ .Values.postgres.database | quote }}
